import Header from '@components/layout/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Oskars',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex-screen ${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
